on:
  workflow_dispatch:
    inputs:
      version:
        description: ""
        type: string
        required: true

name: Create Workflow-Hub GitHub release
run-name: "Workflow-Hub GitHub release v${{ inputs.version }}"
permissions:
  contents: read

jobs:
  check-tag:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        env:
          VERSION: ${{ inputs.version }}
        run: |
          echo "Version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check if tag exists
        id: check_tag
        uses: netcracker/qubership-workflow-hub/actions/tag-action@b575bad3a0959c4e883bc34f9d055ff07fde2dbd #v2.0.1
        with:
          tag-name: "v${{ github.event.inputs.version }}"
          ref: ${{ github.ref }}
          create-tag: false
          check-tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-preparation:
    needs: [check-tag]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up authentication
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          ACTOR: ${{ github.actor }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$REPOSITORY

      - name: Create Release Branch
        env:
          VERSION: ${{ inputs.version }}
        run: |
          git checkout -b "release/v$VERSION"
          git push origin "release/v$VERSION"

      - name: Update references
        env:
          VERSION: ${{ inputs.version }}
        run: |
          # shellcheck disable=2038
          find . -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.md' \) ! -name 'github-release.yml' \
          | xargs sed -i "s|uses: netcracker/qubership-workflow-hub/\(.*\)@main|uses: netcracker/qubership-workflow-hub/\1@v${VERSION}|gi"

      - name: Commit and push changes
        env:
          ACTOR: ${{ github.actor }}
          VERSION: ${{ inputs.version }}
        run: |
          git config --global user.name "$ACTOR"
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Update references to the new version"
          git push origin "release/v$VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

  create-github-release:
    needs: [release-preparation]
    permissions:
      contents: write
    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
    with:
      version: ${{ inputs.version }}
      publish: false
      config-name: release-drafter-config.yml
