---
name: Prettier-fix
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: write

jobs:
  call-prettier-fix:
    uses: netcracker/qubership-workflow-hub/.github/workflows/prettierFix.yaml@v1.0.1
