---
name: Prettier-fix
on: [pull_request, push, workflow_dispatch]

permissions:
  contents: read

jobs:
  call-prettier-fix:
    permissions:
      contents: write
    uses: netcracker/qubership-workflow-hub/.github/workflows/prettierFix.yaml@v2.0.7
